# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: SpacyNLP
    model: en_core_web_trf
    case_sensitive: True
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer
    model_weights: "distilbert-base-uncased"
    model_name: "distilbert"
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    OOV_token: "_oov_"
    min_ngram: 1
    max_ngram: 4
    additional_vocabulary_size:
      text: 1000
  - name: DIETClassifier
    # entity recognition handled by SpaCy-model instead
    entity_recognition: False
    # Training for 30 epochs
    epochs: 50
    # Training/using 2 transformer layers
    num_transformer_layers: 2
    drop_rate: 0.25
    weight_sparsity: 0.7
    batch_size: [64, 256]
    # Setting transformer input size to 512 characters
    transformer_size: 512
  - name: SpacyEntityExtractor
    # dimensions to extract
    dimensions: [ "PERSON", "ORD", "LOC", "GPE", "FAC", "ORG", "MONEY", "ORDINAL", "PRODUCT" ]

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
# policies:
#    - name: MemoizationPolicy
#    - name: TEDPolicy
#      transformer_size: 350
#      max_history: 5
#      epochs: 100
#    - name: RulePolicy
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
